services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 6379:6379


volumes:
  mysql:
